name: CI/CD Pipeline - Deploy Django to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/crud_project
          source env/bin/activate
          cd github-automation-aws/
          git pull origin main
          pip install -r requirements.txt
          python3 manage.py migrate --noinput
          python3 manage.py collectstatic --noinput
